export const CODE_VERIFIER_LOCAL_STORAGE_NAME = 'a12n_ADMIN_UI_CODE_VERIFIER';
export const AUTHORIZATION_CODE_QUERY_PARAM_NAME = 'code';
export const POST_AUTH_REDIRECT_QUERY_PARAM_NAME = 'redirect';
export const POST_AUTH_REDIRECT_PATH_LOCAL_STORAGE_NAME = 'a12n_ADMIN_UI_POST_AUTH_REDIRECT_PATH';
