name: Integration and E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true
  environment: test
  VITE_AUTH_CLIENT_ID: ${{ secrets.VITE_AUTH_CLIENT_ID }}
  VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
  VITE_AUTH_SERVER_URL: ${{ vars.VITE_AUTH_SERVER_URL }}
  VITE_POST_AUTH_REDIRECT_URI: ${{ vars.VITE_POST_AUTH_REDIRECT_URI }}
  VITE_AUTH_SERVER_EMAIL: ${{ secrets.VITE_AUTH_SERVER_EMAIL }}
  VITE_AUTH_SERVER_PASSWORD: ${{ secrets.VITE_AUTH_SERVER_PASSWORD }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Install Docker Compose
      run: sudo apt-get install docker-compose

    - name: Run Playwright tests with Docker Compose
      run: docker-compose up --build --abort-on-container-exit
      
    - name: Copy test results
      if: always()
      run: |
        docker-compose cp playwright-tests:/home/pwuser/playwright-report ./playwright-report
        docker-compose down
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30