name: Integration and E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CI: true
  environment: test
  VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}
  VITE_AUTH_SERVER_URL: ${{ vars.VITE_AUTH_SERVER_URL }}
  VITE_POST_AUTH_REDIRECT_URI: ${{ vars.VITE_POST_AUTH_REDIRECT_URI }}
  VITE_AUTH_SERVER_EMAIL: ${{ vars.VITE_AUTH_SERVER_EMAIL }}
  VITE_AUTH_SERVER_PASSWORD: ${{ vars.VITE_AUTH_SERVER_PASSWORD }}
  JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
jobs:
  playwright:
    name: 'Integration and E2E Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # The following steps are required due to https://github.com/npm/cli/issues/4828
      - name: Clean dependencies
        run: rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run e2e tests
        run: |
          npm run setup:backend
          npx playwright test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
