name: Integration and E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  playwright:
    name: 'Integration and E2E Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      # The following steps are required due to https://github.com/npm/cli/issues/4828
      - name: Clean dependencies
        run: rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run e2e tests
        run: npx playwright test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
